name: 'AdoreMe Tech PHP STAN Composite Action'
description: 'Run PHP STAN'
inputs:
  php-image:
    description: 'The PHP image to use'
    required: true
  report-dir:
    description: 'PHP STAN report directory'
    required: true
    default: 'build/reports'
  report-file-name:
    description: 'PHP STAN report file name'
    required: true
    default: 'php-stan.xml'
runs:
  using: "composite"
  steps:
    - name: 'Run PHP STAN'
      run: $GITHUB_ACTION_PATH/check.sh
      shell: bash
      env:
        INPUT_PHP_IMAGE: ${{ inputs.php-image }}
        INPUT_REPORT_PATH: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
    - name: 'Run PHP STAN Report'
      uses: adore-me/checkstyle-github-action@v1.0.0
      with:
        name: 'PHP STAN'
        title: 'PHP STAN report'
        path: '${{ inputs.report-dir }}/${{ inputs.report-file-name }}'
